export const REQUEST_CREATE_COMMENT = 'REQUEST_CREATE_COMMENT'
export const INVALIDATE_CREATE_COMMENT = 'INVALIDATE_CREATE_COMMENT'
export const COMMENT_HAS_BEEN_CREATED = 'COMMENT_HAS_BEEN_CREATED'

export const INVALIDATE_REMOVE_COMMENT = 'INVALIDATE_REMOVE_COMMENT'
export const REQUEST_REMOVE_COMMENT = 'REQUEST_REMOVE_COMMENT'
export const COMMENT_HAS_BEEN_REMOVED = 'COMMENT_HAS_BEEN_REMOVED'