export const REQUEST_POSTS = 'REQUEST_POSTS'
export const RECEIVE_POSTS = 'RECEIVE_POSTS'
export const INVALIDATE_POSTS = 'INVALIDATE_POSTS'
export const PUSH_LIST_POSTS = 'PUSH_LIST_POSTS'
export const UPDATE_POST_IN_LIST_POSTS = 'UPDATE_POST_IN_LIST_POSTS'
export const REMOVE_POST_IN_LIST_POSTS = 'REMOVE_POST_IN_LIST_POSTS'
export const PUSH_LIST_COMMENTS = 'PUSH_LIST_COMMENTS'
export const REMOVE_COMMENT_IN_LIST_COMMENTS = 'REMOVE_COMMENT_IN_LIST_COMMENTS'

export const REQUEST_POST = 'REQUEST_POST'
export const RECEIVE_POST = 'RECEIVE_POST'
export const INVALIDATE_POST = 'INVALIDATE_POST'

export const RECEIVE_POST_COMMENTS = 'RECEIVE_POST_COMMENTS'

export const POST_HAS_BEEN_REMOVED = 'POST_HAS_BEEN_REMOVED'
export const INVALIDATE_REMOVE_POST = 'INVALIDATE_REMOVE_POST'
export const REQUEST_REMOVE_POST = 'REQUEST_REMOVE_POST'