export const REQUEST_CATEGORIES = 'REQUEST_CATEGORIES'
export const RECEIVE_CATEGORIES = 'RECEIVE_CATEGORIES'
export const INVALIDATE_CATEGORIES = 'INVALIDATE_CATEGORIES'

export const REQUEST_CATEGORY_POSTS = 'REQUEST_CATEGORY_POSTS'
export const RECEIVE_CATEGORY_POSTS = 'RECEIVE_CATEGORY_POSTS'
export const INVALIDATE_CATEGORY_POSTS = 'INVALIDATE_CATEGORY_POSTS'
